### ISSUE TITLE
Find content for initial homepage

### ISSUE THREAD

**Issue by markpfaff** [markpfaff/coffeedigger#17]
Find three real coffees for our first page, pictures, and description

**Comment by luisgamboa** [comment]
I created a google folder where I put the reviews and pictures.

https://drive.google.com/folderview?id=0B-uK9N9khBs1fmNlOHBwWjF0ZTAzY2VnbHh2bkIzY2NzXzhxV21hTm1WamxGd2JWYmhqSzg&usp=sharing
